import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Playfair_Display,
  Roboto_Condensed,
  Roboto, // Add this line
  Poppins,
  Montserrat,
} from "next/font/google";
import SessionProvider from "@/components/providers/sessionProviders";
import "./globals.css";
import { PostHogProvider } from "./providers";
import Header from "@/components/landing/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-playfair",
});
const robotoCondensed = Roboto_Condensed({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto-condensed",
});
const roboto = Roboto({
  // Add this block
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "GoUnplan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} 
          ${playfair.variable} 
          ${geistMono.variable} 
          ${robotoCondensed.variable}
          ${roboto.variable}
          ${poppins.variable}
          ${montserrat.variable}
          antialiased
        `}
      >
        <PostHogProvider>
          <SessionProvider>
            <Header />
            {children}
          </SessionProvider>
        </PostHogProvider>
      </body>
    </html>
  );
}
